[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black   = "#282828"
red     = "#cc241d"
green   = "#98971a"
yellow  = "#d79921"
blue    = "#458588"
magenta = "#b16286"
cyan    = "#689d6a"
white   = "#a89984"

[colors.bright]
black   = "#928374"
red     = "#fb4934"
green   = "#b8bb26"
yellow  = "#fabd2f"
blue    = "#83a598"
magenta = "#d3869b"
cyan    = "#8ec07c"
white   = "#ebdbb2"

[colors.dim]
black   = "#3c3836"
red     = "#9d0006"
green   = "#79740e"
yellow  = "#b57614"
blue    = "#076678"
magenta = "#8f3f71"
cyan    = "#427b58"
white   = "#7c6f64"

[colors.cursor]
cursor = "#d79921"
text = "#282828"

[colors.selection]
text = "#fbf1c7"
background = "#504945"

[colors.hints.start]
background = "#fabd2f"
foreground = "#282828"

[colors.hints.end]
background = "#a89984"
foreground = "#282828"

[colors.search.focused_match]
background = "#b8bb26"
foreground = "#282828"

[colors.search.matches]
background = "#83a598"
foreground = "#282828"

[colors.vi_mode_cursor]
cursor = "#8ec07c"
text = "#282828"
