[colors.bright]
black = "#655c54"
blue = "#458588"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#b16286"
red = "#fb4934"
white = "#fbf1c7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#ebdbb2"
text = "#282828"

[colors.dim]
black = "#282828"
blue = "#83a598"
cyan = "#689d6a"
green = "#98971a"
magenta = "#d3869b"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#282828"
blue = "#83a598"
cyan = "#689d6a"
green = "#98971a"
magenta = "#d3869b"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"


[colors.primary]
background = "#282828"
bright_foreground = "#ebdbb2"
dim_foreground = "#ebdbb2"
foreground = "#ebdbb2"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"

[colors.footer_bar]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"